### ISSUE TITLE
Titles for %sql commands are not correctly parsed

### ISSUE THREAD

**Issue by DaveRuijter** [inspera/blackbricks#10]
Hi! I'm using Azure Databricks and I give most of my commands a title.
Also the sql commands.
Unfortunately those titles are not correctly parsed.
I am not sure what is causing this.. in the example below you can see that the title was "Merge Silver view into Gold".
But it's happening for all the sql commands.

Please see the screenshot below.
![image](https://user-images.githubusercontent.com/5773881/109354209-bf42c000-787d-11eb-96fa-1773fdf3c36e.png)

**Comment by bsamseth** [comment]
Thanks for reporting this. I never even knew you could add titles to cells like that, so I'm not surprised that it isn't handled correctly. Although I'm a bit surprised this is what actually happens. Either way, I will try to update this at some point when I find the time, it shouldn't be a big change. You are more than welcome to make a PR if you want it fixed sooner rather than later! :)

**Comment by bsamseth** [comment]
@DaveRuijter I took a while before I had time to look at blackbricks again, but at least now this should be fixed in version `0.6.6` 👍🏻
