### ISSUE TITLE
Blackbricks forces indentation of two spaces, even when user/notebook setting set to four spaces

### ISSUE THREAD

**Issue by NodeJSmith** [inspera/blackbricks#22]

**Comment by bsamseth** [comment]
By default, yes. The default is 2 spaces because that is what Databricks used to force on you. Now they let you choose, but to be backwards compatible the default used by blackbricks is still 2 spaces. To my knowledge Databricks does not expose notebook settings through any API either, so not much that blackbricks can do about it. 

You'll just have to use the command line option to disable 2 space indentation, and that will work fine.
