### ISSUE TITLE
Can you run blackbricks while using databricks in the browser?

### ISSUE THREAD

**Issue by msmall318** [inspera/blackbricks#27]
For those without a CLI setup, could you run this in the browser version of databricks?
My thought would be `blackbricks.format_notebook('notebook_path', ['notebook_dest'])` with `['notebook_dest']` being an optional argument with the default being `notebook_path` to just update the current notebook.

**Comment by msmall318** [comment]
My thought would be `blackbricks.format_notebook('notebook_path', ['notebook_dest'])` with `['notebook_dest']` being an optional argument with the default being `notebook_path`

**Comment by msmall318** [comment]
Found in the [documentation](https://pypi.org/project/blackbricks/0.4.1/#installation-and-usage) that request is not currently possible

**Comment by bsamseth** [comment]
Hi! There are two ways this _could have_ worked, but none of which work as you would hope:

- The `databricks` CLI is preinstalled on recent Databricks runtimes, but they do not automatically set up credentials for you. If you do configure the `databricks` CLI on a cluster, you could run `blackbricks` just as normal.
  - I have an open feature request to Databricks about them automatically providing credentials for `databricks` CLI. Give it a thumbs up if you'd like Databricks to consider it (I don't have very high expectations, but who knows).
  - https://github.com/databricks/databricks-cli/issues/560
- The notebook file _does_ live on the filesystem that you _can_ get at with a `%sh` cell. This would have been a solution, where you could just run `blackbricks` on the cluster-filesystem file. Sadly, it doesn't work because for some reason you can't access the contents of _notebooks_ via the filesystem. See this example.
![image](https://user-images.githubusercontent.com/8997458/189472047-b378deb3-cd3f-436d-875a-ce550549d424.png)


So, the conclusion is that no, right now you cannot do what you want, and there doesn't seem to be a way for `blackbricks` to work around it either. You need to either sync the notebook as a local file and run `blackbricks` on that before you reupload it, or you'll need to set up `databricks` CLI and run `blackbricks` on the remotely stored notebooks.

**Comment by tedjt** [comment]
We just added support embedded in the notebook web ui for formatting python cells with Black when using DBR 11.2
https://docs.databricks.com/notebooks/notebooks-use.html#format-code-cells on 

Blackbricks is still better for formatting integrated with CI and for bulk formatting many files, but for quick cell level formatting during development, hopefully the new feature works for people.

**Comment by msmall318** [comment]
Thanks for the info. I'll check it out.
