### ISSUE TITLE
Format a string of sql commands contained as text in a spark.sql command.

### ISSUE THREAD

**Issue by msmall318** [inspera/blackbricks#29]
When I run `blackbricks` on a notebook that has a `spark.sql` command with a test string like the code in the picture, it brings the top line down and over to the left but the rest of the code is left untouched. It would be nice if the rest of the sql command was formatted and brought over to the same indentation.

Could the entire sql string be parsed using `parsesql` and then indented?
![image](https://user-images.githubusercontent.com/29266185/189547725-bde1d56d-7861-4af6-a799-9d82d50771ed.png)

**Comment by bsamseth** [comment]
The only formatting that is applied here is what `black` does. `black` is very conservative with how it formats strings, because it never changes what the actual string evaluates to. 

Blackbricks will not support this. This is because it is highly non-trivial to robustly find and reformat such string. Just consider your example: due to the f-string that isn't a valid sql expression that we could give to `sqlparse`. How to handle that? There are also tons of ways to construct a string here, all of which would have to be considered in an implementation. In short, I don't think this is something that should be attempted. 

Better options:
- use pyspark APIs. This is more readable, more flexible and will be formatted. 
- use a sql magic cell. You can't do variable substitution, so I'd advise limiting that to a minimum and just for explorative queries. Use pyspark, it's better for everyone. If it's not a plain query you could put in a sql cell, I will argue strongly that it is much better to use pyspark than to do runtime string manipulation to build the query.
