### ISSUE TITLE
CI/CD integration ?

### ISSUE THREAD

**Issue by de-hru** [inspera/blackbricks#34]
Hi folks!

I didn't find any information related to "run blackbricks automatically in your CI/CD piepline".

Any ideas or experiences out there?

I was thinking about a Git hook ... pre-push would be fine from my point of view.

Dear @bsamseth, should my question be wrong here, please feel free to correct me and point me to the right location!

----
Dejan Hrubenja [dejan.hrubenja@mercedes-benz.com](mailto:dejan.hrubenja@mercedes-benz.com) , Mercedes-Benz Tech Innovation GmbH
https://www.mercedes-benz-techinnovation.com/en/imprint/

**Comment by bsamseth** [comment]
Have you read [this](https://github.com/inspera/blackbricks#version-control-integration) section of the README? That does what you describe. I always use blackbricks with pre-commit. Typically I have notebooks in a separate folder and configure pre-commit so that only blackbricks formats that folder, and other tools (like black) work on the rest of the repo.

**Comment by de-hru** [comment]
> Have you read [this](https://github.com/inspera/blackbricks#version-control-integration) section of the README? That does what you describe.

Shame on me! I have read the manual. In the meanwhile many weeks (or even months) are gone, so I forgot that there was/is a short, clear and understandable recommendation. That's exactly what I've asked for.
THX a lot!
