### ISSUE TITLE
Question: Is it possible to relax the typer version?

### ISSUE THREAD

**Issue by MartinRoth** [inspera/blackbricks#39]
By fixing the typer version to ^0.6.1 I cannot use the latest version of dbx, which requires typer==0.70 (https://github.com/databrickslabs/dbx/blob/main/setup.py). This in turn results in a critical dependabot alert (CVE-2023-0286) for the cryptography module...

**Comment by bsamseth** [comment]
Hi! I'd encourage you to not install blackbricks alongside other things/your project dependencies. Blackbricks is not meant to be used as a library, but rather an application (i.e. the CLI), and as such it is only ever tested with the dependencies listed in its `poetry.lock` file. You'll have a better experience installing it with [pipx](https://pypa.github.io/pipx/) (also mentioned in the README). This is the de-facto way to install Python applications, installing them in their own virtualenv automatically for you. The same probably goes for dbx. This way you can have any number of applications with overlapping dependencies installed, without them interfering with each other or your project dependencies. 

Some notes on the version constraint: The version `^0.6.1` allows versions `>=0.6.1, <0.7` because typer's version still indictes it is in pre-release status (`<1.0`). Ref the [docs for poetry](https://python-poetry.org/docs/dependency-specification/#caret-requirements). While it would _probably_ be fine to use `typer>=0.7`, there's no semver-promise from typer that this would work. Blackbricks will upgrade it's dependencies as needed, or in response to dependabot alerts. Trying to stay on top of all dependencies' updates isn't that practical, and would only serve to give you the same problem in reverse (blackbricks requiring newer versions than other things you install alongside it). 

Hopefully that all sounds reasonable and pipx solves your problem! 👍🏻

**Comment by MartinRoth** [comment]
Hi @bsamseth , 
thank you for your quick reply! 

I try to make the working environment for my colleagues as reproducible as I can, so I use  [pip-tools](https://github.com/jazzband/pip-tools) to create a virtual environment based on a `requirements_dev.txt` file. That means blackbricks is not used in the final application, but the `requirements_dev.txt` file is uploaded to github. Therefore, I came across this issue. Because I can't get this running with the current restrictions, I will not check in blackbricks in our standard development environment as suggested.

Maybe these two links might be of interest to you
- [nine-circles-of-python-dependency-hell](https://medium.com/knerd/the-nine-circles-of-python-dependency-hell-481d53e3e025) 
- https://www.youtube.com/watch?v=Gr9o8MW_pb0 

Cheers,
Martin

**Comment by bsamseth** [comment]
FYI, as part of upgrading the black version to the 2023 version, I've also upgraded typer 👍🏻  https://github.com/inspera/blackbricks/releases/tag/2.1.0
