### ISSUE TITLE
databricks cli is pinned to a very old version

### ISSUE THREAD

**Issue by ianepreston** [inspera/blackbricks#61]
`pyproject.toml` for this project pins `databricks-cli` to `0.17.x`:
`databricks-cli = "^0.17.3"`
The current cli is on `0.225.0`
This means if I add blackbricks into a venv it installs a very old CLI.
Please consider unpinning dependencies, particularly for the CLI.
I know poetry does this by default so I'm guessing this wasn't an intentional choice. I've recently relaxed restrictions in my own libraries.
There's a good discussion of the challenges of this approach here: https://hynek.me/articles/semver-will-not-save-you/

**Comment by bsamseth** [comment]
Hi! The version requirement is very much intentional. Since databricks-cli is <1.0, any "minor version" increase is potentially breaking. blackbricks isn't a library, it's an application. As such, you shouldn't install it (and it's pinned dependencies) next to your library dependencies.  Use pipx for this. See #39 (and other issues mentioning the same issue) for a more in depth answer.
